# Generated by Django 2.0.2 on 2018-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_q', models.CharField(max_length=255)),
                ('question_a', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
